all: compile link

compile:
	g++ main/main.cpp src/utilities.cpp -c -IC:/Users/youss/Documents/SFML-2.5.1/include -IC:/Users/youss/Bureau/info/raycaster2.0/raycasting_in_c++

link:
	g++ main/main.o src/utilities.o -o main -LC:/Users/youss/Documents/SFML-2.5.1/lib -lsfml-graphics -lsfml-window -lsfml-system